font_family GeistMono Nerd Font Mono
font_size   12

disable_ligatures yes
enable_audio_bell no

shell zsh
shell_integration disabled

cursor_shape block

url_style curly

remember_window_size no
initial_window_width 640
initial_window_height 480
window_padding_width 24
cursor_blink_interval 0

background_opacity 0.70 
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0 
confirm_os_window_close 0

sync_to_monitor no

# Colors # Current theme: Dracula
background #1e1f28
foreground #f8f8f2
cursor #bbbbbb
selection_background #44475a
color0 #000000
color8 #545454
color1 #ff5555
color9 #ff5454
color2 #50fa7b
color10 #50fa7b
color3 #f0fa8b
color11 #f0fa8b
color4 #bd92f8
color12 #bd92f8
color5 #ff78c5
color13 #ff78c5
color6 #8ae9fc
color14 #8ae9fc
color7 #bbbbbb
color15 #ffffff
selection_foreground #1e1f28

#Theme desert

#background            #333333
#foreground            #ffffff
#cursor                #00ff00
#selection_background  #b5d5ff
#color0                #4d4d4d
#color8                #545454
#color1                #ff2b2b
#color9                #ff5555
#color2                #98fb98
#color10               #55ff55
#color3                #f0e68c
#color11               #ffff55
#color4                #cd853f
#color12               #87ceff
#color5                #ffdead
#color13               #ff55ff
#color6                #ffa0a0
#color14               #ffd700
#color7                #f5deb3
#color15               #ffffff
#selection_foreground #333333
